# Generated by Django 2.0.6 on 2018-07-13 04:04

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('canberra', django.db.models.manager.Manager()),
            ],
        ),
    ]
